ALTER TABLE public.plans ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.indexed_files ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.indexed_pages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.indexed_frames ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.indexed_owner_usage ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.index_activity_log ENABLE ROW LEVEL SECURITY;
